# GitHub Actions Security Scanning Workflow
# Multi-tool security pipeline with SARIF integration
#
# Copy to: .github/workflows/security-scan.yml

name: Security Scanning

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  schedule:
    - cron: '0 2 * * 1'  # Weekly Monday 2 AM UTC
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  pull-requests: write

jobs:
  # ============================================
  # SECRET DETECTION
  # ============================================

  secrets-scan:
    name: Secret Detection
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_CONFIG: .gitleaks.toml

  # ============================================
  # PYTHON SAST
  # ============================================

  python-sast:
    name: Python SAST (Bandit + Semgrep)
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.7.1
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root

      - name: Run Bandit
        run: |
          poetry run bandit -r apps/ \
            -c pyproject.toml \
            -f sarif \
            -o bandit-results.sarif \
            --exit-zero
        continue-on-error: true

      - name: Upload Bandit SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: bandit-results.sarif
          category: bandit

      - name: Run Semgrep
        run: |
          poetry run semgrep --config .semgrep/ \
            --sarif \
            --output semgrep-results.sarif \
            --exclude node_modules \
            --exclude .venv \
            apps/
        continue-on-error: true

      - name: Upload Semgrep SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: semgrep-results.sarif
          category: semgrep

  # ============================================
  # DEPENDENCY SCANNING
  # ============================================

  dependency-scan:
    name: Dependency Scanning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.7.1
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: apps/frontend/package-lock.json

      - name: Install Python dependencies
        run: poetry install --no-interaction --no-root

      - name: Python dependency scan (pip-audit)
        run: |
          poetry run pip-audit --desc --format json --output pip-audit.json || true
          poetry run pip-audit --desc || true
        continue-on-error: true

      - name: Node dependency scan (npm audit)
        working-directory: apps/frontend
        run: |
          npm ci
          npm audit --json > npm-audit.json || true
          npm audit || true
        continue-on-error: true

      - name: Upload dependency reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: dependency-reports
          path: |
            pip-audit.json
            apps/frontend/npm-audit.json
          retention-days: 30

  # ============================================
  # CONTAINER SCANNING
  # ============================================

  container-scan:
    name: Container Scanning (Trivy)
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    permissions:
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        service: [frontend, enrichment, ingestion, model_service]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build \
            -t example-org/${{ matrix.service }}:${{ github.sha }} \
            -f deploy/Dockerfile.${{ matrix.service }} \
            .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: example-org/${{ matrix.service }}:${{ github.sha }}
          format: sarif
          output: trivy-${{ matrix.service }}.sarif
          severity: CRITICAL,HIGH,MEDIUM
          timeout: 10m0s

      - name: Upload Trivy SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: trivy-${{ matrix.service }}.sarif
          category: trivy-${{ matrix.service }}

      - name: Trivy table output (fail on CRITICAL)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: example-org/${{ matrix.service }}:${{ github.sha }}
          format: table
          exit-code: '1'
          ignore-unfixed: true
          severity: CRITICAL

  # ============================================
  # DOCKERFILE LINTING
  # ============================================

  dockerfile-lint:
    name: Dockerfile Linting (Hadolint)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: deploy/Dockerfile.*
          config: .hadolint.yaml
          format: sarif
          output-file: hadolint.sarif
        continue-on-error: true

      - name: Upload Hadolint SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: hadolint.sarif
          category: hadolint

  # ============================================
  # IAC SCANNING
  # ============================================

  iac-scan:
    name: IaC Security (Checkov)
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          config_file: .checkov.yaml
          output_format: cli,sarif
          output_file_path: console,checkov.sarif
          soft_fail: true

      - name: Upload Checkov SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: checkov.sarif
          category: checkov

  # ============================================
  # SECURITY SUMMARY
  # ============================================

  security-summary:
    name: Security Summary
    runs-on: ubuntu-latest
    needs: [secrets-scan, python-sast, dependency-scan, dockerfile-lint, iac-scan]
    if: always()

    steps:
      - name: Generate summary
        run: |
          echo "## Security Scan Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Scan | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Secrets (Gitleaks) | ${{ needs.secrets-scan.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Python SAST | ${{ needs.python-sast.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Dependency Scan | ${{ needs.dependency-scan.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Dockerfile Lint | ${{ needs.dockerfile-lint.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| IaC Security | ${{ needs.iac-scan.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "View detailed results in the **Security** tab." >> $GITHUB_STEP_SUMMARY

      - name: Fail on critical issues
        if: needs.secrets-scan.result == 'failure'
        run: |
          echo "::error::Secrets detected - blocking merge"
          exit 1
